title: Suzanne Raybuck HITM Blog
description: > # this means to ignore newlines until "baseurl:"
  A blog documenting my honors in the major webcomic. I'm writing, coding, and designing my own webcomic in order to learn more about leveraging digital mediums in for creative storytelling.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "sraybuck.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Suzanne Raybuck # add your name
author-img: headshot.jpg # add your photo
about-author: I'm a senior at FSU working on an honors thesis about webcomics and the rhetoric of composing creatively for the web. # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: sraybuck # add your Github handle
social-linkedin: sraybuck # add your Linkedin handle
social-email: suzraybuck@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
